# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xz3QnoIlUYU9w0O9srYHDKoT_O6_NmxD
"""

from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()

video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join( execution_path, "fruits_table.mp4"),
                                             output_file_path=os.path.join(execution_path, "fruits_table_detected"), 
                                             frames_per_second=29, log_progress=True)
print(video_path)

from imageai.Detection import VideoObjectDetection
import os
import cv2

execution_path = os.getcwd()

camera = cv2.VideoCapture(0) 
#camera = cv2.VideoCapture("http://192.168.1.95") #IP cam
#camera = cv2.VideoCapture("http://192.168.1.63:8080") 

detector = VideoObjectDetection()

#detector.setModelTypeAsYOLOv3()
detector.setModelTypeAsTinyYOLOv3()

#detector.setModelPath(os.path.join(execution_path , "yolo.h5"))
detector.setModelPath( os.path.join(execution_path , "yolo-tiny.h5"))

detector.loadModel(detection_speed="flash")
#detector.loadModel(detection_speed="fastest")
#detector.loadModel(detection_speed="faster")
#detector.loadModel(detection_speed="fast")
#detector.loadModel()

video_path = detector.detectObjectsFromVideo(camera_input=camera,
                                             output_file_path=os.path.join(execution_path, "camera_detected_1"), 
                                             frames_per_second=29,
                                             detection_timeout=120, 
                                             log_progress=True)
print(video_path)

from imageai.Detection import VideoObjectDetection
import os
execution_path = os.getcwd()

detector = VideoObjectDetection()

detector.setModelTypeAsYOLOv3()
#detector.setModelTypeAsTinyYOLOv3()

detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
#detector.setModelPath( os.path.join(execution_path , "yolo-tiny.h5"))

#detector.loadModel(detection_speed="flash")
#detector.loadModel(detection_speed="fastest")
#detector.loadModel(detection_speed="faster")
#detector.loadModel(detection_speed="fast")
detector.loadModel()


video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "pizza.mp4"),
                                             output_file_path=os.path.join(execution_path, "pizza_detected"), 
                                             frames_per_second=29, log_progress=True, 
                                             minimum_percentage_probability=30)

print(video_path)